# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# platform :ios, '9.0'

target 'barosa_me2' do

use_frameworks!


pod 'Firebase/Core'
pod 'Firebase/Firestore'
end